# -*- coding:utf-8 -*-

asis=[" -Asistan programı,kulanıcılara sesli komutlar sayesinde klavye ve mouse kullanımını büyük"
        "ölçüde\nazaltmak için tasarlanmıştır.\n"
        " \n-Asistan programı online bir programdır, internet bağlantınız yoksa çalışmaz!...\n"
        " \n-Program açıldığında her 4-5 saniyede sesli komutlar bekler ve tanımlı komutlara göre\n"
        "işlemi gerçekleştirir.Bilgisayar sizi dinlerken ekranın sağ alt köşesinde mikrofon ikonu görürsünüz.\n"
        " \n-Programı verimli kullanabilmek için HARİCİ MİKROFON kullanmanız TAVSİYE EDİLİR.\n"
        " \n-Sesli komutları anlaşılır ve düzgün gramer ile veriniz.\n"
        " \n-Asistan'a saati,tarihi,hava durumunu,altın,dolar,avro ve bitcoin fiyatlarını sorabilirsiniz.\n"
        " \n-Asistan sizin için Türkçe - İngilizce çeviri yapabilir.\n"
        " \n-Asistan, size haber okuyabilir.\n"
        " \n-Asistan ile Müzik kutusunda oluşturduğunuz müzik listenizden müzik dinleyebilirsiniz.\n"
        " \n-Asistan ile hızlıca not aldırabilirsiniz.\n"
        " \n-Asistan'ın Kontrol modu ile mouse ve klavye ile yapacağınız birçok işi yapabilirsiniz.\n"
        " \n-Programı daha kolay kullanabilmeniz için ASİSTAN penceresinde size ip uçları gösterilecektir.\n"
        "Bu pencerede 'Sen: ... ' kısmı sizin söylediğiniz şeydir.Bu kısmın altındaki boş kısımda da çeşitli\n"
        "bilgi akışları size programı daha rahat kullanmanızı sağlayacaktır.\n"
        " \n-Asistan, hiç bir mod açık değilken yaklaşık olarak 75 dk hiç komut verilmeyince otomatik kapanır."]
kntrl=[" -Kontrol modu Asistan'ın sesli klavye ve mouse'u diyebiliriz.\n"
        "\n -Kontrol modunu açmak için 'kontrol' ya da 'kontrol aç' diyebilirsiniz.\n"
        "\n -Kontrol modu ile üç çeşit teknikle mouse kullanabilirsiniz;\n"
        "   1-Ekranın tam ortasına gelen cursorü sağ/sol-yukarı/aşağı yönlendirerek,\n"
        "   2-'ekranı göster' diyerek açılan 16 ekran bölgesinin numaralarını söyleyip o bölgede\nsağ/sol-yukarı/aşağı yönlendirebilirsiniz,\n"
        "   3-'mouse aç' diyerek sanal mouse açıp çeşitli el hareketleriyle mouse kontrolünü yapabilirsiniz.\n"
        "\n  -Klavye için birçok sesli komutlar var...\n"
        "  -Tüm komutlar detaylı olarak 'KOMUTLAR' kısmında görebilirsiniz.\n"
        "\n -Kontrol modunu kapatmak için 'kontrol kapat' diyebilirsin.\n"
        " -Kontrol modu yaklaşık olarak 40 dk hiç bir komut verilmediği zaman kendiliğinden kapanır.\n"]
ytbe=[" -Youtube modunu açmak için 'youtube aç' kapatmak içinde 'youtube kapat' diyebilirsiniz.\n"
        " \n-Youtube sayfası açıldıktan sonra kontrol modu otomatik açılır.\n"
        " \n-Youtube'de gezinebilirsiniz ya da yeni sekmeler açarak internette gezinmeye devam edebilirsiniz."]
ggle=[" -Google'de arama yapmak için 'google'da arama yap' deyin ve program sizi yönlendirecektir.\n"
        " \n-Arama sayfanız açıldıktan Asistan size aramak istediğiniz soracaktır.Asistan penceresini\ntakip edin.\n"
        " \n-Aramak istediğiniz açıldıktan sonra kontrol modu otomatik açılır ve gezinmeye hazrısınız.\n"
        " \n-Bu mod sadece aramak istediğinizi hızlıca google sayfası açarak arama yapmak için geliştirildi."]
mzk=[" -Müzik modu, siz bilgisayar başında değilken müzik dinlemek istediğinizde kullanmanız için\ngeliştirildi.\n"
        "\n -Müzik kutusuna eklemiş olduğunuz linkleri açarak müzik dinlemenizi sağlar.\n"
        "\n -Bilgisayarı kullanırken müzik modunu kullanmayınız,çünkü program müzik kutunuzdaki linleri\n"
        "açıp kapatarak çalışacaktır.Bilgisayar kullanımızda sorun oluşturur.\n"
        "\n -Müzik modu şimdilik sadece linkler üzerinden çalışmaktadır.İstediğiniz şarkının linkini\n"
        "bularak linkini alınız ve Asistan penceresinde 'Menu' kısmında 'Müzik' e tıklayarak aldığınız\n"
        "linki 'Müzik Linki' kısmına yazınız.'Müzik adı' kısmını boş geçmeyiniz.'KAYDET' e tıkladığınızda\nlistenize eklenecektir.\n"
        "\n -Listenize eklediğiniz müziklerin isimleri Müzik modu komutlarından farklı olmasına dikkat ediniz!\n"
        "\n -Listenizdeki müzikleri öğrenmek için 'kanalları söyle' veya 'müzikleri söyle' demeniz yeterlidir.\n"
        "Fakat listenizde çok sayıda müzik veya kanal varsa listenin hepsini saymayacak ve Asistan bu\nkonuda sizi uyaracaktır.\n"
        "Listenizde çok müzik varsa 'rastgele' veya 'karışık' diyerek rastgele bir müzik açtırabilirsiniz.\n"
        "Veya 'değiştir' diyerek rastgele başka bir müziği açtırabilirsiniz.\n"
        "Ya da dinlemek istediğiniz müziğin kaydettiğiniz şekilde tam adını söyleyerek dinleyebilirsiniz.\n"
        "\n -Sesi kapatmak için 'sesi kapat', sesi açmak için 'sesi aç' , sesi azaltmak için 'sesi azalt',\n"
        "sesi artırmak için 'sesi yükselt' diyebilirsin.\n"
        "\n -Youtube'de mix oluşturup aynı listeyi Müzik listenize eklerseniz Müzik modu çok kullanışlı olur."]
bkle=[" -Bekleme modu, ortamda başka konuşma sesleri oluştuğunda o konuşmalardan komut almaması\n"
        "için eklendi.\n"
        "\n -Bekleme modunu açmak için 'bekle' demeniz yeterlidir.\n"
        "\n -Bekleme modunu kapatmak için 'bilgisayar' ya da profil'de tanımladığınız ismi demeniz yeterlidir.\n"]
ayrlar=[" -Ayarlar'da 3 kısım var:\n"
        "\n  1-Kamera Seçimi:Sanal mouse kullanabilmeniz için kamera gerekiyor.\n"
        "Eğer dahili kameranız varsa program otomatik olarak onu seçecektir.\n"
        "Dilerseniz harici ya da dahili kamera seçimlerini yapabilirsiniz.\n"
        "\n  2-MouseScroll:Açtığınız sayfayı yukarı veya aşağı ne kadar kaydırmak\n"
        "isterseniz ayarlayabilirsiniz.240-960 aralığında değer verebilirsiniz.\n"
        "\n  3-Pencere şeffaflığı:Asistan ana pencerenin şeffaflığını 1-10 aralığında ayarlayabilirsiniz.\n"]
prfl=[" Profil'de programa yeni bir isim tanımlayabilirsiniz:\n"
        "\n  -Böylelikle programı bekleme modundan çıkarmak için o ismi kullanabilirsiniz.\n"
        "\n  -Ya da bazen programa seslenmeniz gerektiğinde tanımladığınız ismi kullanabilirsiniz\n"
        "\n  -Hiçbir isim tanımlamazsanız 'bilgisayar' olarak seslenebilirsiniz.\n"
        "\n Profil'de bulunduğunuz şehir bilgisini girebilirsiniz:\n"
        "\n  -Böylelikle şehrinizin hava durumunu Asistan'a sorabilirsiniz.\n"
        "\n  -Şehir bilgisi girmezseniz 'Karabük' tanımlıdır."]
gzlmod=[" Gizli Mod, ekranı %100 kullanabilmeniz için oluşturuldu.\n"
        "\n -Gizli Mod'u açmak için:'gizli mod aç','gizli modu aç','gizli mod' diyebilirsin,\n"
        "\n -Gizli Mod'u kapatmak için:'gizli mod kapat','gizli modu kapat','kapat gizli modu' diyebilirsin.\n"
        "\n -Gizli Mod'u komutlara alıştıktan sonra kullanmanız daha kullanışlı olacaktır.Çünkü Asistan,\n"
        "size programı kullanabilmeniz için devamlı olarak bilgi gösterecektir."]