#Mouse ve Klavye için komut listeleri

mouse_kntrl=["Kontrol modu açılınca cursor ekranın\ntam ortasına gelir ve aşağıdaki\nkomutlarla mouse'u kontrol edebilirsiniz:\n"
            " -'sağ','doğu','sağ yan','sağ tarafa','sağa'\n'sağ taraf'\n"
            " -'sol','batı','sol yan','sol tarafa','sola',\n'sol taraf'\n"
            " -'yukarı','kuzey'\n"
            " -'aşağı','güney'\n"
            "\n 'ortala' deyince cursor ekranın ortasına\ngelir ve baştan kontrol etmen için hazır\nolur.\n"
            "\nSayfayı aşağı/yukarı kaydırmak için:\n"
            " -'indir','aşağı indir','sayfayı aşağı indir'\n'aşağıyı göster'\n"
            " -'yukarıyı göster','yukarı çık',\n'sayfayı yukarı kaydır','yukarı göster'\n'yukarıya çık'\n"
            "\nTıklamalar için:\n"
            " -Tek tıklamak 'tıkla',\n"
            " -Çift tıklamak 'çift tıkla' diyebilirsin.\n"
            "\nSanal Mouse için:\n"
            " -'mouse aç' deyin ve sanal mouse\n"
            " açılır,sesli komutlar kapanır."
            "\n Daha hassas mouse kullanımı için:\n"
            " -'ekranı göster' derseniz ekran 16'ya\nbölünür "
            "ve cursor'ü istediğiniz yere\ngitmesi için ilgili bölümün numarasını\nsöyleyin."
            "Böylelikle cursor o bölümün\ntam ortasına gider ve o bölümde\nmouse kontrol edersiniz.\n"
            "\n\n........................SAYFA SONU........................"]
klavye_kntrl=["Klavye,kontrol moduyla birlikte kullanılır\n"
                " \n-Önceki sayfaya dönmek için:\n"
                "'geri dön','önceki sayfaya dön'\n'dön geri','dön geriye'\n"
                " -Sonraki sayfaya dönmek için:\n"
                "'sonraki sayfaya dön','sonraki sayfa'\n'ileri sayfa'\n"
                " -Sesi yükseltmek için:\n"
                "'sesi arttır','sesi yükselt','daha fazla ses'\n"
                " -Sesi azaltmak için:\n"
                "'sesi azalt','sesi kıs','azalt sesi'\n"
                " -Sesi açmak/kapatmak için:\n"
                "'sesi kapat','sesi aç','kapat sesi','aç sesi'\n"
                " -İleri sarmak için (sağ yön tuşu):\n"
                "'ileri sar','videoyu ilerlet','video ileri'\n'videoyu ileri sar'\n"
                " -Geri sarmak için (sol yön tuşu):\n"
                "'geri sar','videoyu geri sar','video geri'\n"
                " -Sekme açmak için:\n"
                "'sekme aç' veya 'yeni sekme aç'\n"
                " -Sekme kapatmak için:\n"
                "'sekmeyi kapat' veya 'sekme kapat'\n"
                " -Sekme değiştirmek için:\n"
                "'sekmeyi değiştir' veya 'sekme değiştir'\n"
                " -Yazma modunua açmak için:\n"
                "'dediğimi yaz' veya 'yaz'\n"
                " -Enter için:\n"
                "'enter'\n"
                " -Silmek için (backspace tuşu):\n"
                "'sil'\n"
                " -CTRL+F için:\n"
                "'ara','dediğimi ara','arama yap'\n"
                " -F5 için:\n"
                "'sayfayı yenile'\n"
                " -ESC için:\n"
                "'çık'\n"
                " -window tuşu için:\n"
                "'window' veya 'windows'\n"
                " -Dört işlem için:\n"
                "'topla','toplama işlemi'\n'çıkar','çıkarma işlemi'\n"
                "'çarp','çarpma işlemi'\n'böl','bölme işlemi'"
                "\n\n........................SAYFA SONU........................"]